database:
  driver: mysql
  connection: root:1234@tcp(127.0.0.1:3312)/fruit?charset=utf8&parseTime=True&loc=Local
  logger:
    kafka:
      brokers:
        - 127.0.0.1:9092
      topic: sqllog
eventBroker:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: fruit
behaviorLog:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: behaviorlog
serviceName: go-api-consumer